"""init schema

Revision ID: 9bea1c2d8dd9
Revises: 
Create Date: 2025-10-06 22:56:34.083850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bea1c2d8dd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_code'))

    op.drop_table('schemes')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_citizen_hash'))

    op.drop_table('cases')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('case_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=13), nullable=False),
    sa.Column('actor_type', sa.VARCHAR(), nullable=False),
    sa.Column('actor_id', sa.VARCHAR(), nullable=True),
    sa.Column('payload', sa.VARCHAR(), nullable=True),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('citizen_hash', sa.VARCHAR(), nullable=False),
    sa.Column('scheme_code', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('source', sa.VARCHAR(length=3), nullable=False),
    sa.Column('locale', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['scheme_code'], ['schemes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_citizen_hash'), ['citizen_hash'], unique=False)

    op.create_table('schemes',
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_code'), ['code'], unique=False)

    # ### end Alembic commands ###
